network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      dhcp4: no
      addresses:
        - 10.0.0.50/24
      gateway4: 10.0.0.1
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
